# Generated by Django 5.0.6 on 2024-07-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("idcourse", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("hour", models.PositiveIntegerField()),
                ("credits", models.PositiveIntegerField()),
                ("state", models.BooleanField()),
            ],
        ),
    ]
