# Generated by Django 5.0.6 on 2024-07-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                ("idcareer", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("shortname", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="carreras",default='null')),
                ("state", models.BooleanField()),
            ],
        ),
    ]
